source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.3.3'

gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.1.0'
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'rails', '4.2.0'
gem 'rails-assets-nvd3'
gem 'sass-rails', '~> 5.0'
gem 'simple_form'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'better_errors'
  gem 'byebug'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
  gem 'web-console', '~> 2.0'

  gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 3.4'
  gem 'seed_dump'
end
